# Generated by Django 4.2.7 on 2024-11-03 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('set_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('test', models.CharField(max_length=100)),
                ('cod', models.BigIntegerField(unique=True)),
                ('finish_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('schools', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_last', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('count_correct', models.IntegerField()),
                ('count_wrong', models.IntegerField()),
                ('percent', models.IntegerField()),
                ('correct_str', models.CharField(max_length=100)),
                ('wrong_str', models.CharField(max_length=100)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set_main.createtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set_main.usercreate')),
            ],
        ),
    ]
