# Generated by Django 4.2.7 on 2024-11-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_main', '0002_createtest_usercreate_userresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreate',
            name='male',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
