# Generated by Django 4.2.7 on 2024-11-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_main', '0003_usercreate_male'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottoken',
            name='user_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bottoken',
            name='user_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bottoken',
            name='user_url',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
